name: pal
description: A new Flutter application.
publish_to: 'none'
version: 2.0.6+9
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  carousel_slider:
  fluttertoast:
  dio: ^3.0.10
  shared_preferences:
  image_picker: ^0.6.7+17
  flutter_pdfview: ^1.0.4
  path_provider: ^1.6.24
  file_picker: 1.5.1
  video_player: ^0.10.0+2
  intl:
  url_launcher: ^5.7.10
  flutter_plugin_android_lifecycle: ^1.0.11
  firebase_messaging: ^7.0.3
  firebase_core:
  package_info:
  flutter_local_notifications: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/icons/
   - assets/images/splash-screen.jpg
   - lang/


  fonts:
   - family: Poppins
     fonts:
       - asset: fonts/Poppins-Regular.ttf
